export const STARTING_DECK = [
  {
    id: 'skill_transfer',
    name: '传送',
    type: 'skill',
    cost: 1,
    valueText: '+10',
    tags: ['齿轮'],
    effect: 'teleport',
    text: '弃置双方场上和手牌中的齿轮牌，对方额外弃置1张手牌。本次共弃置几张牌，双方就一起承受对应惩罚：基础+20污染、-10血；每弃置1张再+10污染、-5血。',
    art: '⇄',
  },
  {
    id: 'char_alcoholism',
    name: '酒精症',
    type: 'character',
    cost: 2,
    valueText: '+10',
    hp: 6,
    atk: 0,
    actionCount: 1,
    actionDamage: 6,
    actionShield: 1,
    text: '可行动1次。A：造成6点物伤；B：获得1点护盾。',
    art: '杯',
  },
  {
    id: 'equip_blast_shield',
    name: '防爆盾',
    type: 'equipment',
    cost: 3,
    valueText: '+0',
    text: '本体受到物伤-50%，角色受到物伤-20%，四舍五入。',
    art: '盾',
  },
  {
    id: 'skill_big_chief',
    name: '大首领',
    type: 'skill',
    cost: 0,
    valueText: '+30',
    effect: 'inspectAllHidden',
    text: '触发一张暗置牌，并查看全场暗置牌。',
    art: '冠',
  },
  {
    id: 'skill_memory_inspect',
    name: '记忆检视',
    type: 'skill',
    cost: 2,
    valueText: '+10',
    tags: ['齿轮'],
    effect: 'inspectHidden',
    text: '查看所有敌方暗置牌，并将其移除。',
    art: '眼',
  },
  {
    id: 'scene_refrigeration',
    name: '制冷',
    type: 'scene',
    cost: 2,
    valueText: '+0',
    text: '回合初，我方打出的第一张技能牌无需消耗技能点。',
    art: '冰',
  },
  {
    id: 'scene_great_invasion',
    name: '大侵袭',
    type: 'scene',
    cost: 1,
    valueText: '+5',
    text: '我方物攻+1，每回合-1生命值。',
    art: '刃',
  },
  {
    id: 'skill_metal_cabinet',
    name: '金属柜',
    type: 'hidden',
    subType: 'skill',
    cost: 3,
    valueText: '+10',
    text: '暗置。对方出牌时若造成攻击触发，本回合不受物伤，触发后消失。',
    hiddenTrigger: 'enemyAttackCard',
    effect: 'metalCabinet',
    art: '柜',
  },
  {
    id: 'skill_ancestral_blessing',
    name: '祖上的庇护',
    type: 'hidden',
    subType: 'skill',
    cost: 1,
    valueText: '+0',
    text: '暗置。对方使我方受到污染时触发，本回合不受污染，本回合不可出牌，触发后消失。',
    hiddenTrigger: 'pollutionIncoming',
    effect: 'ancestralBlessing',
    art: '护',
  },
  {
    id: 'skill_mother_love',
    name: '回应……母爱',
    type: 'skill',
    cost: 2,
    valueText: '+50',
    effect: 'motherLove',
    text: '若对方手牌≤3，对方+90污染，-10血。',
    art: '心',
  },
  {
    id: 'hidden_mind_transfer',
    name: '意识转移',
    type: 'hidden',
    subType: 'skill',
    cost: 2,
    valueText: '+20',
    effect: 'mindTransfer',
    hiddenTrigger: 'friendlyCharacterDeath',
    text: '暗置。我方角色死亡时，夺舍场上一个敌方角色，触发后消失。',
    art: '魂',
  },
  {
    id: 'skill_kill',
    name: '殺',
    type: 'skill',
    cost: 2,
    valueText: '+70',
    effect: 'killTarget',
    text: '对敌方一个对象造成40点物伤，可选择敌方角色或敌方本体。',
    art: '杀',
  },
  {
    id: 'char_saintess',
    name: '圣女',
    type: 'character',
    cost: 1,
    valueText: '+0',
    hp: 5,
    atk: 0,
    actionCount: 1,
    actionDamage: 2,
    actionSelfPolluteForSkill: 20,
    text: '可行动1次。A：造成2点物伤；B：可选择自身+20污染，然后获得1点技能点。',
    art: '圣',
  },
  {
    id: 'scene_corpse_land',
    name: '食尸地',
    type: 'scene',
    cost: 0,
    valueText: '+20',
    text: '角色死亡后，为本体+5血。',
    art: '地',
  },
  {
    id: 'skill_ziyou',
    name: '自酉',
    type: 'skill',
    cost: 1,
    valueText: '+25',
    effect: 'ziyou',
    text: '对方-10血，+35污染。',
    art: '酉',
  },
  {
    id: 'hidden_wood_tree',
    name: '木树',
    type: 'hidden',
    subType: 'character',
    cost: 1,
    valueText: '+15',
    hp: 10,
    atk: 0,
    actionCount: 1,
    passiveSkillPerTurn: 1,
    effect: 'woodTree',
    text: '暗置角色。每回合+1技能点。死后变为对方角色。',
    art: '木',
  },
  {
    id: 'hidden_abandoned_carriage',
    name: '抛弃丰厢',
    type: 'hidden',
    subType: 'scene',
    cost: 0,
    valueText: '+30',
    tags: ['齿轮'],
    effect: 'abandonedCarriage',
    hiddenTrigger: 'delayedSecondTurnEnd',
    text: '暗置场景。打出后第二回合末触发：对方-35血，所有角色-4血，触发后消失。',
    art: '厢',
  },
  {
    id: 'skill_golden_apple',
    name: '金苹果',
    type: 'skill',
    cost: 2,
    valueText: '+5',
    effect: 'healSelf',
    value: 15,
    text: '我方本体+15血。',
    art: '苹',
  },
  {
    id: 'scene_control_console',
    name: '警控台',
    type: 'scene',
    cost: 3,
    valueText: '+0',
    tags: ['齿轮'],
    text: '每回合可选择一张牌不消耗技能点使用。',
    art: '控',
  },
  {
    id: 'skill_mad_inspiration',
    name: '疯狂灵感',
    type: 'skill',
    cost: 0,
    valueText: '+20',
    effect: 'drawCards',
    value: 2,
    text: '抽两张牌。',
    art: '灵',
  },
  {
    id: 'skill_teddy_bear',
    name: '小熊',
    type: 'skill',
    cost: 3,
    valueText: '+20',
    effect: 'reduceSelfPollution',
    value: 40,
    text: '污染-40。',
    art: '熊',
  },
  {
    id: 'char_special_employee',
    name: '特殊的"员工"',
    type: 'character',
    cost: 2,
    valueText: '+10',
    hp: 10,
    atk: 0,
    actionCount: 2,
    actionDamage: 5,
    actionShield: 1,
    text: '可行动2次。A：造成5点物伤；B：护盾值+1。',
    art: '员',
  },
  {
    id: 'char_police',
    name: '警察',
    type: 'character',
    cost: 3,
    valueText: '+0',
    hp: 10,
    atk: 0,
    actionCount: 1,
    actionDamage: 6,
    actionShield: 1,
    selfPhysicalReduction: 0.2,
    bodyPhysicalReduction: 0.1,
    text: '可行动1次。A：造成6点物伤；B：获得1点护盾。被动：受物伤-20%，本体减伤10%。',
    art: '警',
  },
  {
    id: 'char_gun',
    name: '枪',
    type: 'character',
    cost: 2,
    valueText: '+0',
    tags: ['齿轮'],
    hp: null,
    noSpirit: true,
    atk: 0,
    untargetableByAttack: true,
    actionCount: 1,
    actionSkillCost: 1,
    actionBodyDamage: 10,
    actionCharacterDamage: 7,
    text: '每回合可消耗1技能点，对敌方本体造成10点物伤，或对一个角色造成7点伤害。',
    art: '枪',
  },
  {
    id: 'char_protector',
    name: '"保卫者"',
    type: 'hidden',
    subType: 'character',
    cost: 3,
    valueText: '+10',
    tags: ['齿轮'],
    hp: 20,
    atk: 0,
    actionCount: 1,
    actionDamage: 8,
    actionShield: 1,
    taunt: true,
    text: '暗置角色。可行动1次。A：造成8点物伤；B：获得1点护盾。被动：嘲讽。',
    art: '卫',
  },
  {
    id: 'hidden_purifier',
    name: '净化器',
    type: 'hidden',
    subType: 'scene',
    cost: 2,
    valueText: '+0',
    tags: ['齿轮'],
    effect: 'purifier',
    hiddenTrigger: 'turnEnd',
    text: '暗置场景。回合末若我方污染≥40，污染-5。',
    art: '净',
  },
  {
    id: 'skill_self_destruct',
    name: '自毁装置',
    type: 'skill',
    cost: 3,
    valueText: '+20',
    effect: 'selfDestruct',
    text: '若本局污染爆发次数≥3，敌方全体-15血、-5精神力。',
    art: '毁',
  },
  {
    id: 'scene_darkness',
    name: '黑暗！',
    type: 'scene',
    cost: 1,
    valueText: '+20',
    effect: 'darknessScene',
    text: '回合初全员-5精神力、+10污染；敌方再-5血、+5污染。',
    art: '暗',
  },
  {
    id: 'skill_id_card',
    name: '身份证',
    type: 'skill',
    cost: 1,
    valueText: '',
    effect: 'shieldCard',
    text: '为一张己方角色牌增加1点护盾值。',
    art: '证',
  },
  {
    id: 'char_monster',
    name: '怪物',
    type: 'character',
    cost: 5,
    valueText: '+20',
    hp: 30,
    atk: 0,
    actionCount: 1,
    actionDamage: 20,
    actionShield: 1,
    damageBonusVsCharacters: 0.2,
    text: '可行动1次。A：造成20点物伤；B：获得1点护盾。被动：对对方角色伤害+20%。',
    art: '怪',
  },
  {
    id: 'food_bread',
    name: '面包',
    type: 'food',
    cost: 0,
    valueText: '',
    effect: 'healSelf',
    value: 5,
    text: '本体恢复5点生命，不能超过生命上限。',
    art: '包',
  },
  {
    id: 'food_enchanted_golden_apple',
    name: '附魔金苹果',
    type: 'food',
    cost: 0,
    valueText: '',
    effect: 'healSelf',
    value: 20,
    text: '本体恢复20点生命，不能超过生命上限。',
    art: '苹',
  },
  {
    id: 'hidden_fall',
    name: '坠落',
    type: 'hidden',
    subType: 'skill',
    cost: 0,
    valueText: '+0',
    effect: 'fall',
    hiddenTrigger: 'enemyNoBurstOrLowSpirit',
    choice: ['spirit25', 'hp40'],
    text: '暗置技能。对方未污染爆发或精神力≤60时触发：出牌玩家选择对方-25精神力或-40血，一次性。',
    art: '坠',
  },
  {
    id: 'scene_banquet',
    name: '宴席',
    type: 'scene',
    cost: 0,
    valueText: '+0',
    effect: 'banquet',
    text: '回合末触发：我方全体角色+1血，本体+4血。',
    art: '宴',
  },
  {
    id: 'hidden_first_aid',
    name: '急救术',
    type: 'hidden',
    subType: 'scene',
    cost: 2,
    valueText: '+15',
    effect: 'firstAid',
    hiddenTrigger: 'lowHp',
    text: '暗置场景。当我方本体血量<20时触发：+25血量。',
    art: '救',
  },
  {
    id: 'skill_abyss_gaze',
    name: '自深渊的凝视',
    type: 'skill',
    cost: 1,
    valueText: '+25',
    effect: 'abyssGaze',
    text: '对方-10精神力，全场角色-5精神力，对方+20污染。',
    art: '凝',
  },
  {
    id: 'char_mtf_agent',
    name: 'MTF特工',
    type: 'character',
    cost: 4,
    valueText: '+0',
    hp: 15,
    atk: 0,
    actionCount: 1,
    actionDamage: 8,
    actionShield: 1,
    pollutionCostReduction: 5,
    friendlyDamageReduction: 1,
    text: '可行动1次。A：8点物伤；B：1点护盾。被动：每次打出手牌污染值-5（下限0），我方受到伤害-1。',
    art: '特',
  },
  {
    id: 'hidden_cleaned_one',
    name: '被清理者',
    type: 'hidden',
    subType: 'character',
    cost: 1,
    valueText: '+15',
    hp: 10,
    spirit: 20,
    atk: 0,
    actionCount: 1,
    actionDamage: 5,
    actionSpiritDamage: 3,
    effect: 'cleanedOne',
    text: '暗置角色。可行动1次：A 5点物伤；B 扣除对方3精神力。出场时将场上所有角色行动改为A 5物伤/B 扣3精神力，并删除原有被动。',
    art: '清',
  },
  {
    id: 'char_extension',
    name: '延展',
    type: 'character',
    cost: 3,
    valueText: '+25',
    hp: 14,
    noSpirit: true,
    atk: 0,
    actionCount: 1,
    actionSpiritDamage: 15,
    actionPolluteEnemy: 15,
    immuneCharacterDamage: true,
    selfHpLossPerTurn: 5,
    text: '无精神力。A：对方-15精神力；B：对方+15污染。被动：免疫角色造成的所有伤害，自己每回合-5血。',
    art: '展',
  },
  {
    id: 'scene_ancestral_hall',
    name: '祖老堂',
    type: 'scene',
    cost: 2,
    valueText: '+0',
    effect: 'ancestralHall',
    text: '我方不受污染。',
    art: '堂',
  },
  {
    id: 'skill_rewind_clock',
    name: '回朔之钟',
    type: 'skill',
    cost: 1,
    valueText: '+30',
    effect: 'rewindClock',
    text: '记录我方所有数据。在我方本体阵亡或下一个我方角色行动回合时，恢复到记录的数据。',
    art: '钟',
  },
  {
    id: 'skill_shadow',
    name: '阴影',
    type: 'skill',
    cost: 2,
    valueText: '+30',
    effect: 'destroyEnemyScene',
    text: '摧毁对方一张场景牌。',
    art: '影',
  },
  {
    id: 'scene_signal_tower',
    name: '信号塔',
    type: 'scene',
    cost: 3,
    valueText: '+0',
    effect: 'signalTower',
    text: '双方每回合初扣除2点精神力。',
    art: '塔',
  },
  {
    id: 'scene_vending_machine',
    name: '贩卖机',
    type: 'scene',
    cost: 2,
    valueText: '+5',
    tags: ['齿轮'],
    effect: 'vendingMachine',
    text: '每回合初我方+10污染、+1技能点；对方+15污染、+1技能点。',
    art: '贩',
  },
  {
    id: 'hidden_blood_test',
    name: '血检',
    type: 'hidden',
    subType: 'skill',
    cost: 1,
    valueText: '+30',
    effect: 'bloodTest',
    hiddenTrigger: 'turnEnd',
    text: '暗置技能。回合结束触发：全角色-5精神力，对方-15精神力；污染爆发n次则对方-5n血；若对方精神力<40则再-5精神力。',
    art: '检',
  },
  {
    id: 'hidden_travelers_blood',
    name: '旅人的鲜血',
    type: 'hidden',
    subType: 'skill',
    cost: 2,
    valueText: '+20',
    tags: ['齿轮'],
    effect: 'travelersBlood',
    hiddenTrigger: 'friendlyCharacterDeath',
    text: '暗置技能。当我方死亡一个角色时触发：全员-5血、-5精神力。',
    art: '血',
  },
  {
    id: 'scene_mountain',
    name: '宀',
    type: 'scene',
    cost: 1,
    valueText: '+40',
    effect: 'mountain',
    maxTriggers: 3,
    text: '每回合末最多触发1次，一共只能触发3次：我方所有角色+1血、+1精神力；本体+3血、+3精神力、-4污染。',
    art: '宀',
  },
  {
    id: 'skill_wordless_book',
    name: '无字天书',
    type: 'skill',
    cost: 1,
    valueText: '+10',
    effect: 'wordlessBook',
    text: '三选一：A污染重置到0，生命上限-5；B本体+50血，生命上限-5；C本体+40精神力，生命上限-5。',
    art: '书',
  },
  {
    id: 'skill_medicine',
    name: '药',
    type: 'skill',
    cost: 1,
    valueText: '+25',
    effect: 'restoreSpirit',
    value: 20,
    text: '回复20精神力。',
    art: '药',
  },
  {
    id: 'char_it',
    name: '它',
    type: 'character',
    cost: 3,
    valueText: '+40',
    hp: null,
    spirit: 3,
    atk: 0,
    actionCount: 1,
    actionSelfSpiritCost: 1,
    effect: 'itEnter',
    actionEffect: 'itAction',
    noSpiritGain: true,
    text: '无血量，5精神力。出场时选择对方一个角色死亡。可行动1次：-1自身精神力，选择对方一个角色死亡；若没有角色，对方-10血量上限、+20污染。不可增加精神力。',
    art: '它',
  },
  {
    id: 'char_orca',
    name: '虎鲸',
    type: 'character',
    cost: 0,
    valueText: '+20',
    hp: 10,
    atk: 0,
    actionCount: 1,
    actionSpiritDamage: 9,
    actionShield: 1,
    effect: 'orcaEnter',
    text: '出场时选择一个角色，该角色护盾失效。可行动1次：A 减少对方9精神力；B 自身+1护盾。',
    art: '鲸',
  },
  {
    id: 'skill_sleeping_pills',
    name: '安眠药',
    type: 'skill',
    cost: 2,
    valueText: '+10',
    effect: 'removeEnemyHidden',
    text: '选择对方一个暗置消除。',
    art: '眠',
  },
  {
    id: 'skill_bangbang',
    name: '！！',
    type: 'skill',
    cost: 1,
    valueText: '+70',
    effect: 'trueBodyStrike',
    text: '对方-40血量、-40精神力。不可防御，无视防御和减伤。',
    art: '!!',
  },
  {
    id: 'skill_memory',
    name: '回忆',
    type: 'skill',
    cost: 1,
    valueText: '+20',
    effect: 'memorySceneRemove',
    text: '移除对方一张场景牌（暗置场景也可以），对方本体-10精神力、+10污染。',
    art: '忆',
  },
  {
    id: 'skill_feeding_contract',
    name: '投喂契约',
    type: 'skill',
    cost: 2,
    valueText: '+20',
    effect: 'feedingContract',
    text: '移除我方一个非齿轮角色：己方本体+20血、+8精神力、+1技能点。若没有可选角色不可打出。',
    art: '契',
  },
];
